version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
      babel:
        patterns:
          - "@babel*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint*"
      storybook:
        patterns:
          - "@storybook/*"
        exclude-patterns:
          - "@storybook/storybook-deployer"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
