export const ROUTES = {
    HOME: '/',
    SEND_BREV_FAGSAK: 'send-brev-fagsak/',
    OPPRETT_JOURNALPOST: '/opprett-journalpost',
    BREV_AVSLUTTET_SAK: '/brev-avsluttet-sak',
    JOURNALPOST_ROOT: '/journalpost/:journalpostid/*',
    PLS_ROOT: 'pleiepenger-i-livets-sluttfase/',
    PSB_ROOT: 'pleiepenger-sykt-barn/',
    OMPKS_ROOT: 'omsorgspenger-kronisk-sykt-barn/',
    OMPMA_ROOT: 'omsorgspenger-midlertidig-alene/',
    OLP_ROOT: 'opplaeringspenger/',
    OMPUT_ROOT: 'omsorgspenger-utbetaling/',
    ALENE_OMSORG_ROOT: 'omsorgspenger-alene-om-omsorgen/',
    KORRIGERING_INNTEKTS_MELDING: 'korrigering-av-inntektsmelding',
    VELG_SOKNAD: 'hentSoknader/',
    PUNCH: `skjema/:id/`,
    KVITTERING: `kvittering/`,
};
