export const ROUTES = {
    HOME: '/',
    AUTH_CALLBACK: '/auth/callback',
    SEND_BREV_FAGSAK: 'send-brev-fagsak/',
    OPPRETT_JOURNALPOST: '/opprett-journalpost',
    BREV_AVSLUTTET_SAK: 'brev-avsluttet-sak/',
    JOURNALPOST_ROOT: '/journalpost/:journalpostid/*',
    PLS_ROOT: 'pleiepenger-i-livets-sluttfase/',
    PSB_ROOT: 'pleiepenger-sykt-barn/',
    OMPKS_ROOT: 'omsorgspenger-kronisk-sykt-barn/',
    OMPMA_ROOT: 'omsorgspenger-midlertidig-alene/',
    OMPAO_ROOT: 'omsorgspenger-alene-om-omsorgen/',
    OLP_ROOT: 'opplaeringspenger/',
    OMPUT_ROOT: 'omsorgspenger-utbetaling/',
    ALENE_OMSORG_ROOT: 'omsorgspenger-alene-om-omsorgen/',
    KORRIGERING_INNTEKTSMELDING: 'korrigering-av-inntektsmelding/',
    KORRIGERING_INNTEKTSMELDING_ID: `korrigering-av-inntektsmelding/:id/`,
    KORRIGERING_ROOT: 'korrigering/',
    VELG_SOKNAD: 'soknader/',
    PUNCH: `skjema/:id/`,
    BREV_BEHANDLET_JP: 'brev-behandlet-journalpost/',
};
