compressionLevel: mixed

enableGlobalCache: false
enableScripts: true

nodeLinker: node-modules

npmScopes:
    navikt:
        npmAlwaysAuth: true
        npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.4.0.cjs
