version: '2'
services:
  k9-punsj:
    image: docker.pkg.github.com/navikt/k9-punsj/k9-punsj
    container_name: k9-punsj
    restart: on-failure
    ports:
      - "8085:8085"
    env_file:
      - "dev-docker/k9-punsj.env"
    depends_on:
      - azure-mock
      - k9-punsj-mocks
    mem_limit: 256m

  oidc-auth-proxy:
    image: docker.pkg.github.com/navikt/oidc-auth-proxy/oidc-auth-proxy
    restart: always
    depends_on:
      - azure-mock
    ports:
      - "8081:8081"
    env_file:
      - "dev-docker/oidc-auth-proxy.env"

  k9-punsj-mocks:
    image: docker.pkg.github.com/navikt/k9-punsj/k9-punsj-mocks
    ports:
      - "8084:8084"

  azure-mock:
    image: docker.pkg.github.com/navikt/azure-mock/azure-mock
    container_name: azure-mock
    ports:
      - "8100:8100"
    mem_limit: 64m