enum HentArbeidsgiverActions {
    HENT_ARBEIDSGIVER_REQUEST = 'HENT_ARBEIDSGIVER_REQUEST',
    HENT_ARBEIDSGIVER_SUCCESS = 'HENT_ARBEIDSGIVER_SUCCESS',
    HENT_ARBEIDSGIVER_FAILED = 'HENT_ARBEIDSGIVER_FAILED',
}
