apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj-oidc-auth-proxy-redis
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: navikt/secure-redis:5.0.3-alpine-2
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m 
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
  vault:
    enabled: true