enum ActionType {
    SET_ARBEIDSGIVERE = 'SET_ARBEIDSGIVERE',
    GET_ARBEIDSGIVERE_FAILED = 'GET_ARBEIDSGIVERE_FAILED',
    SELECT_ARBEIDSGIVER = 'SELECT_ARBEIDSGIVER',
    TOGGLE_GJELDER_ANNEN_ARBEIDSGIVER = 'TOGGLE_GJELDER_ANNEN_ARBEIDSGIVER',
    SET_NAVN_ARBEIDSDGIVER = 'SET_GJELDER_ANNEN_ARBEIDSGIVER',
    SET_SEARCH_ORGANISASJONSNUMMER_FAILED = 'SET_SEARCH_ORGANISASJONSNUMMER_FAILED',
}

export default ActionType;
