apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj-frontend
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: {{ azureTenant }}
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
      - /health/*
      - /logout
  liveness:
    path: health/isAlive
    initialDelay: 20
    periodSeconds: 5
    timeout: 1
    failureThreshold: 10
  readiness:
    path: health/isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    outbound:
      rules:
      {{#each outboundRules as |outboundRule|}}
       - application: {{outboundRule}}
       {{/each}}
      external:
      {{#each outboundExternalHosts as |host|}}
       - host: {{host}}
      {{/each}}
  frontend:
    generatedConfig:
      mountPath: /app/dist/js/nais.js
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  env: 
    - name: PROXY_CONFIG
      value: '{"apis":[
              {{#each proxyRedirects}}
                {"path":"{{path}}", "url":"{{url}}", "scopes":"{{scope}}"}{{#unless @last}},{{/unless}}
              {{/each}}
              ]}'
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
