ingresses:
  - https://k9-punsj-frontend.intern.nav.no
outboundExternalHosts:
  - k9-punsj.prod-fss-pub.nais.io
  - k9-formidling.prod-fss-pub.nais.io
azureTenant: nav.no
proxyRedirects:
  - path: "/k9-punsj/api"
    scope: "api://prod-fss.k9saksbehandling.k9-punsj/.default"
    url: "https://k9-punsj.prod-fss-pub.nais.io"
  - path: "/k9/formidling/api"
    scope: "api://prod-fss.k9saksbehandling.k9-formidling/.default"
    url: "https://k9-formidling.prod-fss-pub.nais.io"
env:
  K9_LOS_URL: https://k9-los-web.nais.adeo.no/
  OMP_KS_ENABLED: "true"
  PLS_ENABLED: "true"
  OMP_MA_FEATURE_TOGGLE: "true"
  OMP_UT_FEATURE_TOGGLE: "true"
  OMP_AO_ENABLED: "true"
  SEND_BREV_OG_LUKK_OPPGAVE_FEATURE_TOGGLE: "true"
  POSTMOTTAK_TOGGLE: "false"
  OLP_ENABLED: "false"
