apiVersion: networking.k8s.io/v1
kind: "Ingress"
metadata:
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://k9-punsj-frontend.dev.adeo.no
  name: k9-punsj-frontend-redirect
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  ingressClassName: gw-dev-intern-nav-no
  rules:
    - host: k9-punsj-frontend.intern.dev.nav.no
      http:
        paths:
          - backend:
              service:
                name: k9-punsj-frontend
                port:
                  number: 80
