 import/prefer-default-export
export enum EksisterendeOMPMASoknaderActionKeys {
    EKSISTERENDE_OMP_MA_SOKNADER_SET = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNADER_SET',
    EKSISTERENDE_OMP_MA_SOKNADER_LOAD = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNADER_LOAD',
    EKSISTERENDE_OMP_MA_SOKNADER_REQUEST_ERROR = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNADER_REQUEST_ERROR',

    EKSISTERENDE_OMP_MA_SOKNAD_OPEN = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNAD_OPEN',
    EKSISTERENDE_OMP_MA_SOKNAD_CLOSE = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNAD_CLOSE',
    EKSISTERENDE_OMP_MA_SOKNAD_CHOOSE = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNAD_CHOOSE',
    EKSISTERENDE_OMP_MA_SOKNAD_UNDO_CHOICE = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNAD_UNDO_CHOICE',

    OMP_MA_SOKNAD_CREATE_REQUEST = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNAD_CREATE_REQUEST',
    OMP_MA_SOKNAD_CREATE_ERROR = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNAD_CREATE_ERROR',
    OMP_MA_SOKNAD_CREATE_SUCCESS = 'PUNCH_EKSISTERENDE_OMP_MA_SOKNAD_CREATE_SUCCESS',

    OMP_MA_SOKNADID_RESET = 'PUNCH_EKSTISTERENDE_OMP_MA_SOKNADID_RESET',
}
