enum Ytelse {
    OMSORGSPENGER_UTBETALING = 'OMP_UT',
    OMSORGSPENGER_UTVIDETRETT_KRONISK_SYKT = 'OMP_UTV_KS',
    OMSORGSPENGER_UTVIDETRETT_MIDLERTIDIG_ALENE = 'OMP_UTV_MA',
    OMSORGSPENGER_UTVIDETRETT_ALENE_OMSORG = 'OMP_UTV_AO',
    OPPLÆRINGSPENGER = 'OPPLÆRINGSPENGER',
    PLEIEPENGER_SYKT_BARN = 'PLEIEPENGER_SYKT_BARN',
    PLEIEPENGER_LIVETS_SLUTTFASE = 'PLEIEPENGER_LIVETS_SLUTTFASE',
}

export default Ytelse;
