 import/prefer-default-export
export enum EksisterendePLSSoknaderActionKeys {
    EKSISTERENDE_PLS_SOKNADER_SET = 'PUNCH_EKSISTERENDE_PLS_SOKNADER_SET',
    EKSISTERENDE_PLS_SOKNADER_LOAD = 'PUNCH_EKSISTERENDE_PLS_SOKNADER_LOAD',
    EKSISTERENDE_PLS_SOKNADER_REQUEST_ERROR = 'PUNCH_EKSISTERENDE_PLS_SOKNADER_REQUEST_ERROR',

    EKSISTERENDE_PLS_SOKNAD_OPEN = 'PUNCH_EKSISTERENDE_PLS_SOKNAD_OPEN',
    EKSISTERENDE_PLS_SOKNAD_CLOSE = 'PUNCH_EKSISTERENDE_PLS_SOKNAD_CLOSE',
    EKSISTERENDE_PLS_SOKNAD_CHOOSE = 'PUNCH_EKSISTERENDE_PLS_SOKNAD_CHOOSE',
    EKSISTERENDE_PLS_SOKNAD_UNDO_CHOICE = 'PUNCH_EKSISTERENDE_PLS_SOKNAD_UNDO_CHOICE',

    PLS_SOKNAD_CREATE_REQUEST = 'PUNCH_EKSISTERENDE_PLS_SOKNAD_CREATE_REQUEST',
    PLS_SOKNAD_CREATE_ERROR = 'PUNCH_EKSISTERENDE_PLS_SOKNAD_CREATE_ERROR',
    PLS_SOKNAD_CREATE_SUCCESS = 'PUNCH_EKSISTERENDE_PLS_SOKNAD_CREATE_SUCCESS',

    PLS_SOKNADID_RESET = 'PUNCH_EKSTISTERENDE_PLS_SOKNADID_RESET',
}
