 import/prefer-default-export
export enum EksisterendeSoknaderActionKeys {
    EKSISTERENDE_SOKNADER_SET = 'PUNCH_EKSISTERENDE_SOKNADER_SET',
    EKSISTERENDE_SOKNADER_LOAD = 'PUNCH_EKSISTERENDE_SOKNADER_LOAD',
    EKSISTERENDE_SOKNADER_REQUEST_ERROR = 'PUNCH_EKSISTERENDE_SOKNADER_REQUEST_ERROR',

    EKSISTERENDE_SOKNAD_OPEN = 'PUNCH_EKSISTERENDE_SOKNAD_OPEN',
    EKSISTERENDE_SOKNAD_CLOSE = 'PUNCH_EKSISTERENDE_SOKNAD_CLOSE',
    EKSISTERENDE_SOKNAD_CHOOSE = 'PUNCH_EKSISTERENDE_SOKNAD_CHOOSE',
    EKSISTERENDE_SOKNAD_UNDO_CHOICE = 'PUNCH_EKSISTERENDE_SOKNAD_UNDO_CHOICE',

    SOKNAD_CREATE_REQUEST = 'PUNCH_EKSISTERENDE_SOKNAD_CREATE_REQUEST',
    SOKNAD_CREATE_ERROR = 'PUNCH_EKSISTERENDE_SOKNAD_CREATE_ERROR',
    SOKNAD_CREATE_SUCCESS = 'PUNCH_EKSISTERENDE_SOKNAD_CREATE_SUCCESS',

    SOKNADID_RESET = 'PUNCH_EKSTISTERENDE_SOKNADID_RESET',
}
