// eslint-disable-next-line import/prefer-default-export
export enum FordelingDokumenttype {
    PLEIEPENGER = 'PLEIEPENGER',
    PLEIEPENGER_I_LIVETS_SLUTTFASE = 'PLEIEPENGER_I_LIVETS_SLUTTFASE',
    KORRIGERING_IM = 'KORRIGERING_IM',
    OMSORGSPENGER_KS = 'OMSORGSPENGER_KS',
    OMSORGSPENGER_MA = 'OMSORGSPENGER_MA',
    OMSORGSPENGER_UT = 'OMSORGSPENGER_UT',
    ANNET = 'ANNET',
}
