enum FordelingFerdigstillJournalpostKeys {
    JOURNALPOST_FERDIGSTILL = 'JOURNALPOST_FERDIGSTILL',
    JOURNALPOST_FERDIGSTILL_SUCCESS = 'JOURNALPOST_FERDIGSTILL_SUCCESS',
    JOURNALPOST_FERDIGSTILL_ERROR = 'JOURNALPOST_FERDIGSTILL_ERROR',
    JOURNALPOST_FERDIGSTILL_RESET = 'JOURNALPOST_FERDIGSTILL_RESET',
}

export default FordelingFerdigstillJournalpostKeys;
