export enum FordelingActionKeys {

    SAKSTYPE_SET = 'FORDELING_SAKSTYPE_SET',

    OMFORDELING_REQUEST = 'FORDELING_OMFORDELING_REQUEST',
    OMFORDELING_SUCCESS = 'FORDELING_OMFORDELING_SUCCESS',
    OMFORDELING_ERROR = 'FORDELING_OMFORDELING_ERROR'
}