enum FordelingFeilregistrerJournalpostKeys {
    JOURNALPOST_FEILREGISTRER = 'JOURNALPOST_FEILREGISTRER',
    JOURNALPOST_FEILREGISTRER_SUCCESS = 'JOURNALPOST_FEILREGISTRER_SUCCESS',
    JOURNALPOST_FEILREGISTRER_ERROR = 'JOURNALPOST_FEILREGISTRER_ERROR',
    JOURNALPOST_FEILREGISTRER_RESET = 'JOURNALPOST_FEILREGISTRER_RESET',
}

export default FordelingFeilregistrerJournalpostKeys;
