enum FordelingSettPåVentKeys {
    JOURNALPOST_SETT_PAA_VENT = 'JOURNALPOST_SETT_PAA_VENT',
    JOURNALPOST_SETT_PAA_VENT_SUCCESS = 'JOURNALPOST_SETT_PAA_VENT_SUCCESS',
    JOURNALPOST_SETT_PAA_VENT_ERROR = 'JOURNALPOST_SETT_PAA_VENT_ERROR',
    JOURNALPOST_SETT_PAA_VENT_RESET = 'JOURNALPOST_SETT_PAA_VENT_RESET',
}

export default FordelingSettPåVentKeys;
