export enum FordelingActionKeys {
    SAKSTYPE_SET = 'FORDELING_SAKSTYPE_SET',
    DOKUMENTTYPE_SET = 'FORDELING_DOKUMENTTYPE_SET',
    FAGSAK_SET = 'FAGSAK_SET',

    OMFORDELING_REQUEST = 'FORDELING_OMFORDELING_REQUEST',
    OMFORDELING_SUCCESS = 'FORDELING_OMFORDELING_SUCCESS',
    OMFORDELING_ERROR = 'FORDELING_OMFORDELING_ERROR',

    SJEKK_SKAL_TIL_K9_REQUEST = 'SJEKK_SKAL_TIL_K9_REQUEST',
    SJEKK_SKAL_TIL_K9_SUCCESS = 'SJEKK_SKAL_TIL_K9_SUCCESS',
    SJEKK_SKAL_TIL_K9_ERROR = 'SJEKK_SKAL_TIL_K9_ERROR',
    SJEKK_SKAL_TIL_K9_JOURNALPOST_STOTTES_IKKE = 'SJEKK_SKAL_TIL_K9_JOURNALPOST_STOTTES_IKKE',
    SJEKK_SKAL_TIL_K9_RESET = 'SJEKK_SKAL_TIL_K9_RESET',

    LUKK_OPPGAVE_REQUEST = 'FORDELING_LUKK_OPPGAVE_REQUEST',
    LUKK_OPPGAVE_SUCCESS = 'FORDELING_LUKK_OPPGAVE_SUCCESS',
    LUKK_OPPGAVE_ERROR = 'FORDELING_LUKK_OPPGAVE_ERROR',
    LUKK_OPPGAVE_RESET = 'FORDELING_LUKK_OPPGAVE_RESET',

    GOSYS_GJELDER_REQUEST = 'GOSYS_GJELDER_REQUEST',
    GOSYS_GJELDER_SUCCESS = 'GOSYS_GJELDER_SUCCESS',
    GOSYS_GJELDER_ERROR = 'GOSYS_GJELDER_ERROR',

    IDENT_BEKREFT_IDENT1 = 'FORDELING_BEKREFT_IDENT1',
    VALGT_GOSYS_KATEGORI = 'VALGT_GOSYS_KATEGORI',

    RESET_FORDELING = 'RESET_FORDELING',
}
