 import/prefer-default-export
export enum GosysOppgaveActionKeys {
    OPPRETT_OPPGAVE_REQUEST = 'OPPRETT_GOSYS_OPPGAVE_REQUEST',
    OPPRETT_OPPGAVE_SUCCESS = 'OPPRETT_GOSYS_OPPGAVE_SUCCESS',
    OPPRETT_OPPGAVE_ERROR = 'OPPRETT_GOSYS_OPPGAVE_ERROR',
    OPPRETT_OPPGAVE_RESET = 'OPPRETT_GOSYS_OPPGAVE_RESET',
}
