export enum PunchActionKeys {

    IDENT_SET = 'PUNCH_IDENT_SET',
    STEP_SET = 'PUNCH_STEP_SET',

    JOURNALPOST_SET = 'PUNCH_JOURNALPOST_SET',
    JOURNALPOST_LOAD = 'PUNCH_JOURNALPOST_LOAD',
    JOURNALPOST_REQUEST_ERROR = 'PUNCH_JOURNALPOST_REQUEST_ERROR',

    MAPPER_SET = 'PUNCH_MAPPER_SET',
    MAPPER_LOAD = 'PUNCH_MAPPER_LOAD',
    MAPPER_REQUEST_ERROR = 'PUNCH_MAPPER_REQUEST_ERROR',
    MAPPER_UNDO_SEARCH = 'PUNCH_MAPPER_UNDO_SEARCH',

    MAPPE_OPEN = 'PUNCH_MAPPE_OPEN',
    MAPPE_CLOSE = 'PUNCH_MAPPE_CLOSE',
    MAPPE_CHOOSE = 'PUNCH_MAPPE_CHOOSE',
    MAPPE_NEW = 'PUNCH_MAPPE_NEW',
    MAPPE_UNDO_CHOICE = 'PUNCH_MAPPE_UNDO_CHOICE',

    FAGSAKER_SET = 'PUNCH_FAGSAKER_SET',
    FAGSAKER_LOAD = 'PUNCH_FAGSAKER_LOAD',
    FAGSAKER_REQUEST_ERROR = 'PUNCH_FAGSAKER_REQUEST_ERROR',

    FAGSAK_OPEN = 'PUNCH_FAGSAK_OPEN',
    FAGSAK_CLOSE = 'PUNCH_FAGSAK_CLOSE'
}