export enum PunchFormActionKeys {
    MAPPE_LOAD = 'PUNCH_FORM_MAPPE_LOAD',
    MAPPE_REQUEST_ERROR = 'PUNCH_FORM_MAPPE_REQUEST_ERROR',
    MAPPE_SET = 'PUNCH_FORM_MAPPE_SET',
    MAPPE_RESET = 'PUNCH_FORM_MAPPE_RESET',
    SOKNAD_SET = 'PUNCH_FORM_SOKNAD_SET'
}