export enum PunchFormActionKeys {

    RESET = 'PUNCH_FORM_RESET',

    SOKNAD_LOAD = 'PUNCH_FORM_SOKNAD_LOAD',
    SOKNAD_REQUEST_ERROR = 'PUNCH_FORM_SOKNAD_REQUEST_ERROR',
    SOKNAD_SET = 'PUNCH_FORM_SOKNAD_SET',
    SOKNAD_RESET = 'PUNCH_FORM_SOKNAD_RESET',

    SOKNAD_UPDATE_REQUEST = 'PUNCH_FORM_SOKNAD_UPDATE_REQUEST',
    SOKNAD_UPDATE_SUCCESS = 'PUNCH_FORM_SOKNAD_UPDATE_SUCCESS',
    SOKNAD_UPDATE_ERROR = 'PUNCH_FORM_SOKNAD_UPDATE_ERROR',

    SOKNAD_SUBMIT_REQUEST = 'PUNCH_FORM_SOKNAD_SUBMIT_REQUEST',
    SOKNAD_SUBMIT_SUCCESS = 'PUNCH_FORM_SOKNAD_SUBMIT_SUCCESS',
    SOKNAD_SUBMIT_UNCOMPLETE = 'PUNCH_FORM_SOKNAD_SUBMIT_UNCOMPLETE',
    SOKNAD_SUBMIT_ERROR = 'PUNCH_FORM_SOKNAD_SUBMIT_ERROR',

    HENT_PERIODER_REQUEST = 'HENT_PERIODER_REQUEST',
    HENT_PERIODER_SUCCESS = 'HENT_PERIODER_SUCCESS',
    HENT_PERIODER_ERROR = 'HENT_PERIODER_ERROR',
}
