export enum PunchFormActionKeys {

    RESET = 'PUNCH_FORM_RESET',

    MAPPE_LOAD = 'PUNCH_FORM_MAPPE_LOAD',
    MAPPE_REQUEST_ERROR = 'PUNCH_FORM_MAPPE_REQUEST_ERROR',
    MAPPE_SET = 'PUNCH_FORM_MAPPE_SET',
    MAPPE_RESET = 'PUNCH_FORM_MAPPE_RESET',

    SOKNAD_UPDATE_REQUEST = 'PUNCH_FORM_SOKNAD_UPDATE_REQUEST',
    SOKNAD_UPDATE_SUCCESS = 'PUNCH_FORM_SOKNAD_UPDATE_SUCCESS',
    SOKNAD_UPDATE_ERROR = 'PUNCH_FORM_SOKNAD_UPDATE_ERROR',

    SOKNAD_SUBMIT_REQUEST = 'PUNCH_FORM_SOKNAD_SUBMIT_REQUEST',
    SOKNAD_SUBMIT_SUCCESS = 'PUNCH_FORM_SOKNAD_SUBMIT_SUCCESS',
    SOKNAD_SUBMIT_UNCOMPLETE = 'PUNCH_FORM_SOKNAD_SUBMIT_UNCOMPLETE',
    SOKAND_SUBMIT_ERROR = 'PUNCH_FORM_SOKNAD_SUBMIT_ERROR'
}