export enum PunchActionKeys {

    IDENT_SET = 'PUNCH_IDENT_SET',
    STEP_SET = 'PUNCH_STEP_SET',
    BACK_FROM_FORM = 'PUNCH_MAPPEID_RESET',

    JOURNALPOST_SET = 'PUNCH_JOURNALPOST_SET',
    JOURNALPOST_LOAD = 'PUNCH_JOURNALPOST_LOAD',
    JOURNALPOST_REQUEST_ERROR = 'PUNCH_JOURNALPOST_REQUEST_ERROR',

    BACK_FROM_MAPPER = 'PUNCH_MAPPER_UNDO_SEARCH'
}