export enum PunchActionKeys {

    IDENT_SET = 'PUNCH_IDENT_SET',

    MAPPER_SET = 'PUNCH_MAPPER_SET',
    MAPPER_LOAD = 'PUNCH_MAPPER_LOAD',
    MAPPER_REQUEST_ERROR = 'PUNCH_MAPPER_REQUEST_ERROR',
    MAPPER_UNDO_SEARCH = 'PUNCH_MAPPER_UNDO_SEARCH',

    MAPPE_OPEN = 'PUNCH_MAPPE_OPEN',
    MAPPE_CLOSE = 'PUNCH_MAPPE_CLOSE',
    MAPPE_CHOOSE = 'PUNCH_MAPPE_CHOOSE',
    MAPPE_NEW = 'PUNCH_MAPPE_NEW',
    MAPPE_UNDO_CHOICE = 'PUNCH_MAPPE_UNDO_CHOICE'
}