export enum Sakstype {
    PLEIEPENGER_SYKT_BARN = 'PLEIEPENGER_SYKT_BARN',
    OMSORGSPENGER = 'OMSORGSPENGER',
    OPPLAERINGSPENGER = 'OPPLAERINGSPENGER',
    PLEIEPENGER_I_LIVETS_SLUTTFASE = 'PLEIEPENGER_I_LIVETS_SLUTTFASE',
    ANNET = 'ANNET'
}