export enum SoknaderSokActionKeys {

    IDENT_SET = 'PUNCH_IDENT_SET',
    STEP_SET = 'PUNCH_STEP_SET',
    BACK_FROM_FORM = 'PUNCH_MAPPEID_RESET',
    BACK_FROM_MAPPER = 'PUNCH_MAPPER_UNDO_SEARCH',
    RESET = 'PUNCH_RESET'
}
