 import/prefer-default-export
export enum SoknaderVisningActionKeys {
    SOKNADER_SET = 'PUNCH_SOKNADER_SET',
    SOKNADER_LOAD = 'PUNCH_SOKNADER_LOAD',
    SOKNADER_REQUEST_ERROR = 'PUNCH_SOKNADER_REQUEST_ERROR',
    SOKNADER_FORBIDDEN_ERROR = 'SOKNADER_FORBIDDEN_ERROR',

    SOKNAD_OPEN = 'PUNCH_SOKNAD_OPEN',
    SOKNAD_CLOSE = 'PUNCH_SOKNAD_CLOSE',
    SOKNAD_CHOOSE = 'PUNCH_SOKNAD_CHOOSE',
    SOKNAD_UNDO_CHOICE = 'PUNCH_SOKNAD_UNDO_CHOICE',

    SOKNAD_CREATE_REQUEST = 'PUNCH_SOKNAD_CREATE_REQUEST',
    SOKNAD_CREATE_ERROR = 'PUNCH_SOKNAD_CREATE_ERROR',
    SOKNAD_CREATE_SUCCESS = 'PUNCH_SOKNAD_CREATE_SUCCESS',

    SOKNADID_RESET = 'PUNCH_SOKNADID_RESET',
}
