export enum TimeFormat {
    DATE_WITH_MONTH_NAME = 'DATE_WITH_MONTH_NAME',
    DATE_WITH_SHORT_MONTH_NAME = 'DATE_WITH_SHORT_MONTH_NAME',
    DATE_SHORT = 'DATE_SHORT',
    DATE_RANGE = 'DATE_RANGE',
}
