apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj-oidc-auth-proxy
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{oidcAuthProxyImage}}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: {{azureTenant}}
      replyURLs:
      {{#each ingresses as |url|}}
        - {{url}}/oidc/callback
      {{/each}}
  liveness:
    path: isalive
    initialDelay: 20
    periodSeconds: 5
    timeout: 1
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
  webproxy: true
  filesFrom:
    - secret: k9-punsj-oidc-auth-proxy-cookie-secrets
      mountPath: /var/run/secrets/cookie
    - secret: k9-punsj-oidc-auth-proxy-redis-password
      mountPath: /var/run/secrets/redis
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
    - name: PROXY_CONFIG
      value: 'value:{"apis":[{"path":"k9-punsj","scopes":"{{k9PunsjScopes}}","url":"http://k9-punsj.k9saksbehandling.svc.nais.local/api"},{"path":"k9-formidling","scopes":"{{k9FormidlingScopes}}","url":"http://k9-formidling.k9saksbehandling.svc.nais.local/k9/formidling/api"}]}'
    - name: REDIS_HOST
      value: value:k9-punsj-oidc-auth-proxy-redis.k9saksbehandling.svc.nais.local
    - name: REDIS_PORT
      value: value:6379
    - name: SESSION_ID_COOKIE_NAME
      value: value:k9-punsj-frontend
    - name: CORS_ALLOWED_HEADERS
      value: value:Content-Type,Referer,X-Nav-NorskIdent
    - name: CORS_EXPOSED_HEADERS
      value: value:Location
    - name: CLIENT_ID
      value: env:AZURE_APP_CLIENT_ID
    - name: DISCOVERY_URL
      value: env:AZURE_APP_WELL_KNOWN_URL
    - name: JWK
      value: path:/var/run/secrets/nais.io/azure/AZURE_APP_JWK
    - name: REDIS_PASSWORD
      value: path:/var/run/secrets/redis/REDIS_PASSWORD
    - name: SESSION_ID_COOKIE_SIGN_SECRET
      value: path:/var/run/secrets/cookie/SESSION_ID_COOKIE_SIGN_SECRET
    - name: SESSION_ID_COOKIE_VERIFY_SECRET
      value: path:/var/run/secrets/cookie/SESSION_ID_COOKIE_VERIFY_SECRET
