apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj-oidc-auth-proxy-redis
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
  annotations:
    nais.io/run-as-group: "0"
    nais.io/read-only-file-system: "false"
spec:
  image: bitnami/redis:7.0.5
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m 
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
  envFrom:
    - secret: k9-punsj-oidc-auth-proxy-redis-password
