apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: k9-punsj-oidc-auth-proxy
    namespace: default
    labels:
        team: k9saksbehandling
spec:
    image: docker.pkg.github.com/navikt/oidc-auth-proxy/oidc-auth-proxy:2019.12.06-95f3f31
    port: 8080
    liveness:
        path: isalive
        initialDelay: 20
        periodSeconds: 5
        timeout: 1
        failureThreshold: 10
    readiness:
        path: isready
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://k9-punsj-oidc-auth-proxy.nais.preprod.local
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: false
        path: /metrics
    vault:
      enabled: true
      paths:
        - mountPath: /var/run/secrets/nais.io/vault
          kvPath: /kv/preprod/fss/k9-punsj-oidc-auth-proxy/default
        - mountPath: /var/run/secrets/nais.io/azuread
          kvPath: /azuread/data/dev/creds/k9-punsj-oidc-auth-proxy
    webproxy: true
    env:
        - name: CLIENT_ID
          value: 304cf945-d49f-43e7-b6a4-5ad6a08e0589
        - name: DISCOVERY_URL
          value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
        - name: LOGIN_SCOPES
          value: 'openid profile 304cf945-d49f-43e7-b6a4-5ad6a08e0589/.default'
        - name: OIDC_AUTH_PROXY_BASE_URL
          value: https://k9-punsj-oidc-auth-proxy.nais.preprod.local
        - name: APPLICATION_BASE_URL
          value: https://k9-punsj-frontend.nais.preprod.local
        - name: ALLOW_PROXY_TO_SELF_SIGNED_CERTIFICATES
          value: 'true'
        - name: SESSION_ID_COOKIE_NAME
          value: k9-punsj-frontend
        - name: PROXY_CONFIG
          value: '{"apis":[{"path":"k9-punsj","url":"https://k9-punsj.nais.preprod.local/api","scopes":"3ccdda02-eaf5-4c75-af01-ea0ee7d01819/.default"}]}'
        - name: REDIS_HOST
          value: k9-punsj-oidc-auth-proxy-redis.default.svc.nais.local
        - name: REDIS_PORT
          value: '6379'
        - name: CORS_ALLOWED_HEADERS
          value: 'Content-Type,Referer,X-Nav-NorskIdent'
        - name: CORS_EXPOSED_HEADERS
          value: 'Location'
