apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: k9-punsj-frontend
    namespace: default
    labels:
        team: k9saksbehandling
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: health/isAlive
        initialDelay: 20
        periodSeconds: 5
        timeout: 1
        failureThreshold: 10
    readiness:
        path: health/isReady
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://k9-punsj-frontend.dev.adeo.no
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    env:
        - name: OIDC_AUTH_PROXY
          value: https://k9-punsj-oidc-auth-proxy.dev.adeo.no
        - name: K9_LOS_URL
          value: https://k9-los-web.dev.adeo.no/
