apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj-frontend
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
  annotations:
    nais.io/run-as-user: "101" # Fix permissions for nginx
    nais.io/read-only-file-system: "false" # Fix permissions for nginx
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: {{ azureTenant }}
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
      - /dist/*
      - /getEnvVariables

  liveness:
    path: /isAlive
    initialDelay: 20
    periodSeconds: 5
    timeout: 1
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
      {{#each outboundExternalHosts as |host|}}
       - host: {{host}}
      {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
