name: Copilot Setup Steps

on:
    workflow_dispatch:
    push:
        paths:
            - .github/workflows/copilot-setup-steps.yml
    pull_request:
        paths:
            - .github/workflows/copilot-setup-steps.yml

jobs:
    copilot-setup-steps:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
        steps:
            - name: Hente kode
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken ${{ secrets.GITHUB_TOKEN }}

            - name: Sette opp Node
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 20.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'

            - name: Installere moduler
              run: yarn install --immutable
