name: Copilot Setup Steps

on:
    workflow_dispatch:
    push:
        paths:
            - .github/workflows/copilot-setup-steps.yml
    pull_request:
        paths:
            - .github/workflows/copilot-setup-steps.yml

jobs:
    copilot-setup-steps:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
        steps:
            - name: Hente kode
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken ${{ secrets.GITHUB_TOKEN }}

            - name: Sette opp Node
              uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
              with:
                  node-version: 20.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'

            - name: Installere moduler
              run: yarn install --immutable
