name: Deploy redirect
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to (dev or prod)'
                required: true
                type: choice
                options:
                    - dev
                    - prod

permissions:
    contents: read
    id-token: write

jobs:
    deploy-redirect-gcp:
        name: Deploye redirect fra ${{github.event.inputs.environment}}-fss til ${{github.event.inputs.environment}}-gcp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - name: Deploye til dev
              uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
              env:
                  CLUSTER: ${{ github.event.inputs.environment }}-fss
                  RESOURCE: nais/${{ github.event.inputs.environment }}-fss-redirect.yml
