name: Deploy redirect
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to (dev or prod)'
                required: true
                type: choice
                options:
                    - dev
                    - prod

permissions:
    contents: read
    id-token: write

jobs:
    deploy-redirect-gcp:
        name: Deploye redirect fra ${{github.event.inputs.environment}}-fss til ${{github.event.inputs.environment}}-gcp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
            - name: Deploye til dev
              uses: nais/deploy/actions/deploy@8a6fb62e73f837af6287d5db84a46ea96aa6c30d # v2
              env:
                  CLUSTER: ${{ github.event.inputs.environment }}-fss
                  RESOURCE: nais/${{ github.event.inputs.environment }}-fss-redirect.yml
