name: Lint

on:
    workflow_call:
        secrets:
            READER_TOKEN:
                required: true

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read
        steps:
            - name: Hente kode
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - name: Configure Yarn for GitHub Packages
              uses: ./.github/actions/configure-yarn
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Sette opp Node
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: 22.22.3
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'

            - name: Installere moduler
              run: yarn install --immutable
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Sjekke opp mot Lint-regler
              run: yarn run lint
