name: Lint

on:
  workflow_call:

jobs:
  test:
    name: Tester
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3.0.2
      - name: Sette opp Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"
          cache: "yarn"
      - uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: .
      - name: Kjøre tester
        run: yarn test --maxWorkers=2
