name: Validere pull request
on:
    pull_request:
        types: [opened, synchronize]

permissions:
    contents: read

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        secrets:
            READER_TOKEN: ${{ secrets.READER_TOKEN }}

    test:
        uses: ./.github/workflows/test.yml
        secrets:
            READER_TOKEN: ${{ secrets.READER_TOKEN }}

    test-cypress:
        uses: ./.github/workflows/cypress-tester.yml
        secrets:
            READER_TOKEN: ${{ secrets.READER_TOKEN }}
    build:
        uses: ./.github/workflows/build.yml
        secrets:
            READER_TOKEN: ${{ secrets.READER_TOKEN }}

    sif-code-scan:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - uses: navikt/sif-gha-workflows/.github/actions/sif-code-scan@v1
